### PR TITLE
JWT access/refresh tokens implementation

### PR DESCRIPTION
**Pull request by EmileCalixte**
| Q             | A
| ------------- | ---
| Is bugfix?    | No
| New feature?  | Yes
| Fixed issues  |

### CODE REVIEW

**Comment by EmileCalixte** [comment]
I've called function called by router "**action**Something", let me know if you think that's good or not

**Review by alexisljn — CHANGES_REQUESTED** [review]
I think It would be better if Controller receive parameters from the router and return result to Router. By this way, each part of our app have a single responsability.

I'd like that the array you passed in AuthController.verifyToken be switched to an constant array of the class. 

Plus i think for understanding, you should use plural instead of singular for expectedTypes in this very same method

**Comment by EmileCalixte** [comment]
Thanks for your review ! I'll change that !

**Comment by EmileCalixte** [comment]
@alexisljn You can re-review 😄

**Review by alexisljn — APPROVED** [review]
Great Work !

**Review by aekix — APPROVED** [review]

**Pull request merged**
