### PR TITLE
Added expirationDate column and userId nullable in refresh token table

### PR DESCRIPTION
**Pull request by EmileCalixte**
| Q             | A
| ------------- | ---
| Is bugfix?    | No
| New feature?  | No
| Fixed issues  | 

This will allow us to store guests refresh tokens in this table, and to run a periodic task to remove expired refresh tokens from the table.

### CODE REVIEW

**Comment by EmileCalixte** [comment]
Review required ! It will be pretty simple, but please tell me what you think about that.

**Comment by aekix** [comment]
We need it but there is not a another way to store this out of the database to avoid requesting all the time the db?

**Comment by EmileCalixte** [comment]
I think this is not a problem: an access token has a lifetime of 15 minutes, so this table will not be oversolicited.

**Review by alexisljn — APPROVED** [review]
Nice job

**Pull request merged**
