### PR TITLE
Generation Of Sequelize Models And Relations

### PR DESCRIPTION
**Pull request by alexisljn**
| Q             | A
| ------------- | ---
| Is bugfix?    | No
| New feature?  | Yes
| Fixed issues  | Fixes # if any

Optional description...

### CODE REVIEW

**Comment by alexisljn** [comment]
Review Requested !

**Review by EmileCalixte — COMMENTED** [review]
Great job ! Just one thing about the file tree, wouldn't it be better if directory `db_models` was named `dbModels` ?

**Comment by alexisljn** [comment]
I don't know if it would be better but I can do it. Therefore it has to be our convention name for folders.

**Comment by EmileCalixte** [comment]
Yes, I think camelCase is a good practice for naming folders and files.

**Comment by alexisljn** [comment]
Review Required !

**Review by EmileCalixte — APPROVED** [review]
Great !

**Review by aekix — APPROVED** [review]

**Comment by alexisljn** [comment]
Don't merge !!

**Pull request merged**
